// <auto-generated />
using System;
using AnimalFarmsMarket.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ProductionMigrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210713012306_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.Address", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("character varying(125)")
                        .HasMaxLength(125);

                    b.Property<string>("DateCreated")
                        .HasColumnType("text");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("character varying(125)")
                        .HasMaxLength(125);

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("character varying(125)")
                        .HasMaxLength(125);

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.Agent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccountName")
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<string>("Bank")
                        .HasColumnType("text");

                    b.Property<string>("BusinessLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateCreated")
                        .HasColumnType("text");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("text");

                    b.Property<string>("NIN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NINTrackingId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.Property<byte>("Gender")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.Property<string>("PublicId")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("ZipCode")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.BroadcastNews", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateCreated")
                        .HasColumnType("text");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("text");

                    b.Property<int>("Dislikes")
                        .HasColumnType("integer");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .HasColumnType("text");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("character varying(125)")
                        .HasMaxLength(125);

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BroadCastNews");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DateCreated")
                        .HasColumnType("text");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(125)")
                        .HasMaxLength(125);

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.Comment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BroadCastNewsId")
                        .HasColumnType("text");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("character varying(125)")
                        .HasMaxLength(125);

                    b.Property<string>("DateCreated")
                        .HasColumnType("text");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BroadCastNewsId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.DeliveryAssignment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DateCreated")
                        .HasColumnType("text");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("text");

                    b.Property<string>("DeliveryPersonId")
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryPersonId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("DeliveryAssignments");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.DeliveryMode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DateCreated")
                        .HasColumnType("text");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("DeliveryModes");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.DeliveryPerson", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<string>("Coverage")
                        .IsRequired()
                        .HasColumnType("character varying(125)")
                        .HasMaxLength(125);

                    b.Property<string>("CoverageLocation")
                        .IsRequired()
                        .HasColumnType("character varying(125)")
                        .HasMaxLength(125);

                    b.Property<string>("DateCreated")
                        .HasColumnType("text");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("text");

                    b.Property<string>("NIN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NINTrackingId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("DeliveryPersons");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.Livestock", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasMaxLength(10);

                    b.Property<string>("AgentId")
                        .HasColumnType("text");

                    b.Property<bool>("Availability")
                        .HasColumnType("boolean");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.Property<string>("CategoryId")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("character varying(25)")
                        .HasMaxLength(25);

                    b.Property<string>("DateCreated")
                        .HasColumnType("text");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("MarketId")
                        .HasColumnType("text");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasMaxLength(10);

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<byte>("Sex")
                        .HasColumnType("smallint")
                        .HasMaxLength(25);

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18, 6)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MarketId");

                    b.ToTable("LiveStocks");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.LivestockImages", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DateCreated")
                        .HasColumnType("text");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<string>("LivestockId")
                        .HasColumnType("text");

                    b.Property<string>("PublicId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LivestockId");

                    b.ToTable("LivestockImages");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.Market", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DateCreated")
                        .HasColumnType("text");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("text");

                    b.Property<string>("MarketName")
                        .IsRequired()
                        .HasColumnType("character varying(125)")
                        .HasMaxLength(125);

                    b.HasKey("Id");

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.MarketAddress", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("character varying(125)")
                        .HasMaxLength(125);

                    b.Property<string>("DateCreated")
                        .HasColumnType("text");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("text");

                    b.Property<string>("MarketId")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("character varying(125)")
                        .HasMaxLength(125);

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("character varying(125)")
                        .HasMaxLength(125);

                    b.HasKey("Id");

                    b.HasIndex("MarketId")
                        .IsUnique();

                    b.ToTable("MarketAddresses");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DateCreated")
                        .HasColumnType("text");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("text");

                    b.Property<string>("DeliveryDate")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DeliveryModeId")
                        .HasColumnType("text");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("PaymentMethodId")
                        .HasColumnType("text");

                    b.Property<byte>("PaymentStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("ShippedTo")
                        .IsRequired()
                        .HasColumnType("character varying(125)")
                        .HasMaxLength(125);

                    b.Property<string>("ShippingPlanId")
                        .HasColumnType("text");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnName("CustomerId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryModeId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("ShippingPlanId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.OrderItems", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DateCreated")
                        .HasColumnType("text");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("text");

                    b.Property<string>("LivestockId")
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LivestockId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.Partner", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DateCreated")
                        .HasColumnType("text");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.PaymentMethod", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DateCreated")
                        .HasColumnType("text");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.Rating", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DateCreated")
                        .HasColumnType("text");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("text");

                    b.Property<string>("LivestockId")
                        .HasColumnType("text");

                    b.Property<int>("RatingFigure")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LivestockId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DateCreated")
                        .HasColumnType("text");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("text");

                    b.Property<string>("LivestockId")
                        .HasColumnType("text");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LivestockId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.ShippingPlan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Coverage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateCreated")
                        .HasColumnType("text");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("text");

                    b.Property<decimal>("DeliveryCost")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int>("DeliveryPeriod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ShippingPlans");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.Testimony", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DateCreated")
                        .HasColumnType("text");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("text");

                    b.Property<string>("Testimonies")
                        .IsRequired()
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("character varying(125)")
                        .HasMaxLength(125);

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Testimonies");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.TrackingHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DateCreated")
                        .HasColumnType("text");

                    b.Property<string>("DateUpdated")
                        .HasColumnType("text");

                    b.Property<string>("DeliveryPersonId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryPersonId");

                    b.HasIndex("OrderId");

                    b.ToTable("TrackingHistories");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.Address", b =>
                {
                    b.HasOne("AnimalFarmsMarket.Data.Models.AppUser", "User")
                        .WithOne("Address")
                        .HasForeignKey("AnimalFarmsMarket.Data.Models.Address", "UserId");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.Agent", b =>
                {
                    b.HasOne("AnimalFarmsMarket.Data.Models.AppUser", "AppUser")
                        .WithOne("Agent")
                        .HasForeignKey("AnimalFarmsMarket.Data.Models.Agent", "AppUserId");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.BroadcastNews", b =>
                {
                    b.HasOne("AnimalFarmsMarket.Data.Models.AppUser", "User")
                        .WithMany("Broadcasts")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.Comment", b =>
                {
                    b.HasOne("AnimalFarmsMarket.Data.Models.BroadcastNews", "BroadcastNews")
                        .WithMany("Comments")
                        .HasForeignKey("BroadCastNewsId");

                    b.HasOne("AnimalFarmsMarket.Data.Models.AppUser", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.DeliveryAssignment", b =>
                {
                    b.HasOne("AnimalFarmsMarket.Data.Models.DeliveryPerson", "DeliveryPerson")
                        .WithMany("DeliveryAssignments")
                        .HasForeignKey("DeliveryPersonId");

                    b.HasOne("AnimalFarmsMarket.Data.Models.Order", "Order")
                        .WithOne("DeliveryAssignment")
                        .HasForeignKey("AnimalFarmsMarket.Data.Models.DeliveryAssignment", "OrderId");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.DeliveryPerson", b =>
                {
                    b.HasOne("AnimalFarmsMarket.Data.Models.AppUser", "AppUser")
                        .WithOne("DeliveryPerson")
                        .HasForeignKey("AnimalFarmsMarket.Data.Models.DeliveryPerson", "AppUserId");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.Livestock", b =>
                {
                    b.HasOne("AnimalFarmsMarket.Data.Models.Agent", "Agent")
                        .WithMany("Livestocks")
                        .HasForeignKey("AgentId");

                    b.HasOne("AnimalFarmsMarket.Data.Models.Category", "Category")
                        .WithMany("Livestocks")
                        .HasForeignKey("CategoryId");

                    b.HasOne("AnimalFarmsMarket.Data.Models.Market", "Market")
                        .WithMany("Livestocks")
                        .HasForeignKey("MarketId");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.LivestockImages", b =>
                {
                    b.HasOne("AnimalFarmsMarket.Data.Models.Livestock", "Livestock")
                        .WithMany("Images")
                        .HasForeignKey("LivestockId");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.MarketAddress", b =>
                {
                    b.HasOne("AnimalFarmsMarket.Data.Models.Market", "Market")
                        .WithOne("MarketAddress")
                        .HasForeignKey("AnimalFarmsMarket.Data.Models.MarketAddress", "MarketId");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.Order", b =>
                {
                    b.HasOne("AnimalFarmsMarket.Data.Models.DeliveryMode", "DeliveryMode")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryModeId");

                    b.HasOne("AnimalFarmsMarket.Data.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentMethodId");

                    b.HasOne("AnimalFarmsMarket.Data.Models.ShippingPlan", "ShippingPlan")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingPlanId");

                    b.HasOne("AnimalFarmsMarket.Data.Models.AppUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.OrderItems", b =>
                {
                    b.HasOne("AnimalFarmsMarket.Data.Models.Livestock", "Livestock")
                        .WithMany("OrderDetails")
                        .HasForeignKey("LivestockId");

                    b.HasOne("AnimalFarmsMarket.Data.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.Rating", b =>
                {
                    b.HasOne("AnimalFarmsMarket.Data.Models.Livestock", "Livestock")
                        .WithMany("Ratings")
                        .HasForeignKey("LivestockId");

                    b.HasOne("AnimalFarmsMarket.Data.Models.AppUser", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.Review", b =>
                {
                    b.HasOne("AnimalFarmsMarket.Data.Models.Livestock", "Livestock")
                        .WithMany("Reviews")
                        .HasForeignKey("LivestockId");

                    b.HasOne("AnimalFarmsMarket.Data.Models.AppUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.Testimony", b =>
                {
                    b.HasOne("AnimalFarmsMarket.Data.Models.AppUser", "User")
                        .WithMany("Testimonies")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("AnimalFarmsMarket.Data.Models.TrackingHistory", b =>
                {
                    b.HasOne("AnimalFarmsMarket.Data.Models.DeliveryPerson", "DeliveryPerson")
                        .WithMany("TrackingHistory")
                        .HasForeignKey("DeliveryPersonId");

                    b.HasOne("AnimalFarmsMarket.Data.Models.Order", "Order")
                        .WithMany("TrackingHistories")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AnimalFarmsMarket.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AnimalFarmsMarket.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalFarmsMarket.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AnimalFarmsMarket.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
